### ISSUE TITLE
AmbiguousRuleException: Rules 10 and 9 are ambiguous

### ISSUE THREAD

**Issue by pascaltimshel** [perslab/CELLECT#25]
Dataset contains cell-types  GABA11, GABA12 ..

```
(rkm916_default) -bash-4.2$ snakemake --use-conda -s cellect-ldsc.snakefile
Loading default config file: config-ldsc.yml
Building DAG of jobs...
AmbiguousRuleException:
Rules 10 and 9 are ambiguous for the file /scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/per_annotation/chen2017__G
ABA1.1.l2.ldscore.gz.
Consider starting rule output with a unique prefix, constrain your wildcards, or use the ruleorder directive.
Wildcards:
        10: BASE_OUTPUT_DIR=/scratch/timshel/BMIcelltypes/CELLECT-LDSC,chromosome=1,run_prefix=chen2017
        9: BASE_OUTPUT_DIR=/scratch/timshel/BMIcelltypes/CELLECT-LDSC,chromosome=1,run_prefix=chen2017
Expected input files:
        10: /scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.M /scratch/timshel/BMIcellt
ypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.M_5_50 /scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation
/chen2017/chen2017.COMBINED_ANNOT.1.log /scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.an
not.gz /scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.ldscore.gz
        9: /scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.M /scratch/timshel/BMIcellty
pes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.M_5_50 /scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation/
chen2017/chen2017.COMBINED_ANNOT.1.log /scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.ann
ot.gz /scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.ldsc

.. [continues] ..

.../scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/per_annotation/chen2017__cir
cadian_3_Per2.1.l2.M /scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/per_annotation/chen2017__circadian_3_Per2.1.l2.
M_5_50 /scratch/timshel/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/per_annotation/chen2017__circadian_3_Per2.1.annot.gz
```

**Comment by pascaltimshel** [comment]
@JonThom : is it a mistake that the .gz is missing in your 'report' of the error? (Error during copy/paste)
![image](https://user-images.githubusercontent.com/5487016/65775143-e7d20200-e13f-11e9-9e30-8ba9743dd0ee.png)

**Comment by pascaltimshel** [comment]
It is possible that we need further wildcard contraints to  'rule: # split_LD_scores': https://github.com/perslab/CELLECT/blob/master/cellect-ldsc.snakefile#L560.

**Comment by JonThom** [comment]
commit `60034a2cc06a6297410a9bdb72d7744fcd48fa65`

issue still occurs with the chen2017 dataset.

relevant lines from `config-ldsc.yml`:

`SPECIFICITY_INPUT:`
  `- id: romanov2017`
   `  path: /projects/jonatan/tools/sc-genetics/timshel-bmicelltypes2019/out/es/romanov2017.mu.csv.gz`

**Comment by JonThom** [comment]
> @JonThom : is it a mistake that the .gz is missing in your 'report' of the error? (Error during copy/paste)

Yes copy/paste error!

**Comment by pascaltimshel** [comment]
Still thinking about how to resolve this issue.

In the mean time: 
path `/projects/jonatan/tools/sc-genetics/timshel-bmicelltypes2019/out/es/romanov2017.mu.csv.gz` does not exist anymore.
Can you send me the new path?

**Comment by pascaltimshel** [comment]
@JonThom 

1: can you paste in the annotation names in this thread?

2: can you try to rename your annotations in the `.mu.csv.gz` file and rerun?
Here are some suggestions for renaming:
- add suffix to each annotation: `_mysuffix`
- name annotations `annot1`, `annot2`, ..., `annotn`

**Comment by JonThom** [comment]
> In the mean time:
> path /projects/jonatan/tools/sc-genetics/timshel-bmicelltypes2019/out/es/romanov2017.mu.csv.gz does not exist anymore.
> Can you send me the new path?

Moved folder, new path is:
`/projects/jonatan/pub-perslab/timshel-bmicelltypes2019/out/es/romanov2017.mu.csv.gz`

**Comment by JonThom** [comment]
> 1: can you paste in the annotation names in this thread?

Astro
Ependy
Epith1
Epith2
GABA1
GABA10
GABA11
GABA12
GABA13
GABA14
GABA15
GABA16
GABA17
GABA18
GABA2
GABA3
GABA4
GABA5
GABA6
GABA7
GABA8
GABA9
Glu1
Glu10
Glu11
Glu12
Glu13
Glu14
Glu15
Glu2
Glu3
Glu4
Glu5
Glu6
Glu7
Glu8
Glu9
Hista
IMO
Macro
Micro
MO
OPC
POPC
Tany

**Comment by JonThom** [comment]
> 2: can you try to rename your annotations in the .mu.csv.gz file and rerun?

will try with suffixes

**Comment by JonThom** [comment]
Chen analysis seems to be running after adding "_clust" suffix

**Comment by Tobi1kenobi** [comment]
Problem was that wildcards were being shared between the ambiguous rules meaning output from different datasets were given the same dataset name. This will work fine usually but produce poorly named files however becomes an issue when two sc datasets have common cell-type names (as Romanov 2017 and Chen 2017 do).

Resolved by adding a wildcard constraint, run_prefix = prefix, in the 'split_LD_scores' rule. Will push the fix soon.

**Comment by pascaltimshel** [comment]
Problem should be resolved now as described by @Tobi1kenobi. Commit: https://github.com/perslab/CELLECT/commit/4036cc52880e222f7805fda2daf58f87469bc3fe
