### ISSUE TITLE
python3: can't open file 'scripts/parse_results_cmdline.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by JonThom** [perslab/CELLECT#28]
> [...] /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/out/prioritization/romanov2017__SYSTOLICadjMED_UKBB_Loh2018.cell_type_results.txt, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/out/prioritization/romanov2017__T1D_Bradfield2011.cell_type_results.txt, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/out/prioritization/romanov2017__T2D_DIAMANTE_Mahajan2018.cell_type_results.txt, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/out/prioritization/romanov2017__T2D_UKBB_Loh2018.cell_type_results.txt, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/out/prioritization/romanov2017__UC_Jostins2012.cell_type_results.txt, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/out/prioritization/romanov2017__WHR_Pulit2019.cell_type_results.txt, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/out/prioritization/romanov2017__WHRadjBMI_Pulit2019.cell_type_results.txt, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/out/prioritization/romanov2017__WHRadjBMI_UKBB_Loh2018.cell_type_results.txt, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/out/prioritization/romanov2017__WORRY_Nagel2018.cell_type_results.txt
>     output: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/results/prioritization.csv
>     output: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/results/prioritization.csv
>     jobid: 1
>     wildcards: BASE_OUTPUT_DIR=/scratch/rkm916/BMIcelltypes/CELLECT-LDSC
> 
> python3: can't open file 'scripts/parse_results_cmdline.py': [Errno 2] No such file or directory
> [Fri Oct 11 04:53:44 2019]
> Error in rule parse_results:
>     jobid: 1
>     output: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/results/prioritization.csv
>     shell:
>         python3 scripts/parse_results_cmdline.py --base_output_dir /scratch/rkm916/BMIcelltypes/CELLECT-LDSC
>         (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
> 
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/log/2019-10-10T122854.199803.snakemake.log

**Comment by Tobi1kenobi** [comment]
Pushed a hotfix and tested on command line, should work fine now. But would like your OK @pascaltimshel before I close this issue.

**Comment by pascaltimshel** [comment]
Problem resolved: https://github.com/perslab/CELLECT/commit/2e1ae2262be496f00eebc387ba692f16c865cab3
(Sorry for this stupid error)
