### ISSUE TITLE
development branch: Error in rule compute_LD_scores

### ISSUE THREAD

**Issue by JonThom** [perslab/CELLECT#30]
> [Tue Oct 15 10:38:09 2019]
> Finished job 233.
> 67 of 434 steps (15%) done
> 
> [Tue Oct 15 10:38:09 2019]
> rule compute_LD_scores:
>     input: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.annot.gz
>     output: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.ldscore.gz, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.M, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.M_5_50, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.log
>     log: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/logs/log.compute_LD_scores.chen2017.1.txt
>     jobid: 216
>     wildcards: BASE_OUTPUT_DIR=/scratch/rkm916/BMIcelltypes/CELLECT-LDSC, run_prefix=chen2017, chromosome=1
> 
> Activating conda environment: /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/conda/565c9f04
> [Tue Oct 15 10:38:10 2019]
> Error in rule compute_LD_scores:
>     jobid: 216
>     output: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.ldscore.gz, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.M, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.l2.M_5_50, /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.log
>     log: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/logs/log.compute_LD_scores.chen2017.1.txt (check log file(s) for error message)
>     conda-env: /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/conda/565c9f04
>     shell:
>         /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/ldsc/ldsc.py --l2 --bfile /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/data/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.1 --ld-wind-cm 1            --annot /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1.annot.gz                --thin-annot --out /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/precomputation/chen2017/chen2017.COMBINED_ANNOT.1                --print-snps /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/data/ldsc/print_snps.txt &> /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/logs/log.compute_LD_scores.chen2017.1.txt
>         (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
> 
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: /nfsdata/projects/jonatan/tools/sc-genetics/CELLECT/.snakemake/log/2019-10-15T094002.552519.snakemake.log

**Comment by JonThom** [comment]
To reproduce, go to `/projects/jonatan/tools/sc-genetics/CELLECT/` and run `snakemake --use-conda -s cellect-ldsc.snakefile`

**Comment by Tobi1kenobi** [comment]
Issue seems to be that you don't have anything in the `ldsc` directory (see the rule-specific log file returned above `log: /scratch/rkm916/BMIcelltypes/CELLECT-LDSC/logs/log.compute_LD_scores.chen2017.1.txt`). I tried copying your config file to my CELLECT directory and got it to work fine.

I don't know how this happened but I'd recommend cloning again just to be ure you have everything. We're hopefully going to implement tests to check that everything is cloned properly (see #26).
