### ISSUE TITLE
munge_sumstats.py / mtag_munge.py hanging

### ISSUE THREAD

**Issue by liubovpashkova** [perslab/CELLECT#32]
After running the tutorial example as follows:

` ./munge_sumstats.py --sumstats ../example/GWAS_EA_excl23andMe.txt.gz --merge-alleles ../data/ldsc/w_hm3.snplist --N 766345.0 --out ../example/EA3_Lee2018`

I got the both munge_sumstats.py / mtag_munge.py hanging and not responding after the following lines:
```
Reading list of SNPs for allele merge from ../data/ldsc/w_hm3.snplist
Read 1217311 SNPs for allele merge.
Reading sumstats from ../example/GWAS_EA_excl23andMe.txt.gz into memory 5000000 SNPs at a time.
...
```

As assumed at [https://github.com/bulik/ldsc/issues/112](https://github.com/bulik/ldsc/issues/112), I managed to solve the problem by fixing the modules to have exactly the following versions:

```
name: ldsc
channels:
- bioconda
dependencies:
- python=2.7
- bitarray=0.8
- nose=1.3
- pybedtools=0.7
- pip
- pip:
  - scipy==0.18
  - pandas==0.20
  - numpy==1.12
```

I suggest that the enviroment fix (environment.yml) for conda >= 4.7 from [https://github.com/bulik/ldsc](https://github.com/bulik/ldsc) should be added in order for our  example data mungling to work properly. 
P. S.: my current conda version is 4.7.12

**Comment by pascaltimshel** [comment]
@liubovpashkova : can you do `conda list`?

Any problems should be fixed in this commit: https://github.com/perslab/CELLECT/commit/e49e1a4513af4cd08972ca323f2ca36ff7e41cf9 

See also https://github.com/perslab/CELLECT/issues/36
