### ISSUE TITLE
Check GWAS input 

### ISSUE THREAD

**Issue by pascaltimshel** [perslab/CELLECT#47]
Check for GWAS input:
- file(s) exist(s)
- correct formated (columns, data types etc)
- possibly other factors

Make explicit error/warning if input is not compatible with LDSC / MAGMA

**Comment by liubovpashkova** [comment]
- Snakemake itself checks for missing input files and throws very descriptive errors if there are  missing ones.
- Columns check added for both LDSC and MAGMA (see WiKi).
