### ISSUE TITLE
Tabula Muris dataset

### ISSUE THREAD

**Issue by fadista** [perslab/CELLECT#48]
Hi,

In your CELLECT/CELLEX manuscript you worked mainly with Tabula Muris and the Mouse Nervous System datasets, right? The Mouse Nervous System dataset was easily converted to a format ready to be used by CELLECT but, as far as I can see the Tabula Muris original files are dispersed into one Robj file per tissue (https://figshare.com/articles/Robject_files_for_tissues_processed_by_Seurat/5821263). Do you have those Tabula Muris files already preprocessed and ready to be input into CELLECT? That would be great! Thanks.

Best,
João

**Comment by Tobi1kenobi** [comment]
Hi João,

The precomputed CELLEX datasets can all be found in the wiki, [here](https://github.com/perslab/CELLECT/wiki/Precomputed-CELLEX-datasets). 

Hope that's helpful,
Tobi

**Comment by fadista** [comment]
Excellent! Thanks a lot.

Best,
João
