### ISSUE TITLE
WINDOW_LD_BASED analysis error

### ISSUE THREAD

**Issue by fadista** [perslab/CELLECT#49]
Hi,

I used CELLECT with the WINDOW_SIZE_KB option and all went well. But when I use the WINDOW_LD_BASED option (I turn it to 'True'), I get the following error message:

Traceback (most recent call last):
  File "/home/people/jpsfad/CELLECT/1.1.0/.snakemake/scripts/tmpq0e1txdm.join_SNPsnap_and_bim_snake.py", line 79, in <module>
    join_SNPsnap_bim_SNPs_to_input_bim(bimfile_path, out_dir, SNPsnap_file, list_chromosomes)
  File "/home/people/jpsfad/CELLECT/1.1.0/.snakemake/scripts/tmpq0e1txdm.join_SNPsnap_and_bim_snake.py", line 51, in join_SNPsnap_bim_SNPs_to_input_bim
    print('{} SNPs were lost in the joining process'.format(np.sum(left_joined_SNPs.loc[:,'rsID_snap'].isna())))
  File "/home/people/jpsfad/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'isna'
[Tue Apr 28 09:55:55 2020]
Error in rule join_snpsnap_bims:
    jobid: 115
    output: 
/home/people/jpsfad/CELLECT/1.1.0/CELLECT-LDSC-FS_mousebrain_LD/precomputation/SNPsnap/SNPs_with_genes.1000G.EUR.QC.1.txt 

 Do you know what might be the problem?,
Thanks, João

**Comment by Tobi1kenobi** [comment]
Hi João,

It seems like a bug has crept into this part of the code, I'll be able to look into about fixing it within a few weeks. In our experience using physical distance produces better results but I'll update this thread when it is fixed so you can try for yourself.

All the best,
Tobi

**Comment by pascaltimshel** [comment]
hi @fadista , we have decided to retire the `WINDOW_LD_BASED` feature as our benchmarks (unpublished) did not show increased performance over `WINDOW_SIZE_KB` and `WINDOW_LD_BASED` results in significantly slower computation time.
