### ISSUE TITLE
ERROR converting summary statistics

### ISSUE THREAD

**Issue by satzel** [perslab/CELLECT#50]
Hello,

I tried to run mtag_munge.py using:

python ldsc/mtag_munge.py \
--sumstats example/meta_stats_all.txt \
--a1 REF \
--a2 ALT \
--merge-alleles data/ldsc/w_hm3.snplist \
--n-value 263595 \
--keep-pval \
--p Pval \
--out example/gwas_out

My file header looks like this:

CHR	POS	REF	ALT	SNP	all_meta_N	BETA	all_inv_var_meta_sebeta	Pval
1	10563	C	G	1:10563:C:G	1	-1.51e+00	1.57e+00	3.38e-01
1	13289	CCT	C	1:13289:CCT:C	1	-9.07e-01	6.75e-01	1.79e-01

and this is the output I get:

Call: 
./munge_sumstats.py \
--out example/ICP_gwas \
--merge-alleles data/ldsc/w_hm3.snplist \
--n-value 263595 \
--a1 REF \
--a2 ALT \
--sumstats example/ICP_FG_DC_EG_DBDS_meta_stats_all.txt \
--p Pval 

Interpreting column names as follows:
Pval:	p-Value
ALT:	a2, interpreted as non-ref allele for signed sumstat.
REF:	a1, interpreted as ref allele for signed sumstat.
BETA:	[linear/logistic] regression coefficient (0 --> no effect; above 0 --> A1 is trait/risk increasing)
SNP:	Variant ID (e.g., rs number)

Reading list of SNPs for allele merge from data/ldsc/w_hm3.snplist
Read 1217311 SNPs for allele merge.
Reading sumstats from example/ICP_FG_DC_EG_DBDS_meta_stats_all.txt into memory 5000000 SNPs at a time.

ERROR converting summary statistics:

Traceback (most recent call last):
  File "ldsc/mtag_munge.py", line 892, in munge_sumstats
    dat = parse_dat(dat_gen, cname_translation, merge_alleles, args)
  File "ldsc/mtag_munge.py", line 477, in parse_dat
    dat = pd.concat(dat_list, axis=0).reset_index(drop=True)
  File "/opt/anaconda3/envs/munge_ldsc/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 206, in concat
    copy=copy)
  File "/opt/anaconda3/envs/munge_ldsc/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 239, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

Conversion finished at Mon May  4 11:36:41 2020
Total time elapsed: 2.0m:1.84s
Traceback (most recent call last):
  File "ldsc/mtag_munge.py", line 969, in <module>
    d = munge_sumstats(parser.parse_args(), write_out=True)
  File "ldsc/mtag_munge.py", line 892, in munge_sumstats
    dat = parse_dat(dat_gen, cname_translation, merge_alleles, args)
  File "ldsc/mtag_munge.py", line 477, in parse_dat
    dat = pd.concat(dat_list, axis=0).reset_index(drop=True)
  File "/opt/anaconda3/envs/munge_ldsc/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 206, in concat
    copy=copy)
  File "/opt/anaconda3/envs/munge_ldsc/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 239, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

Do I have to translate the SNPs into rsIDs for this to run?

Thanks

**Comment by pascaltimshel** [comment]
Hi @satzel ,

Yes you have to convert SNPs to rsIDs. Please let us know if this resolved your issue.

**Comment by satzel** [comment]
Thanks Pascal, it resolved that problem, but I ran into the next one. ~ 70% of my SNPs get filtered out in the  --merge-alleles step. Is it a problem when the annotation is based on build38? I couldn't find any documentation on that... 

Thanks :)

**Comment by pascaltimshel** [comment]
That is as expected as the `--merge-alleles` argument restricts your SNPs to SNPs contained in HapMap3. This is currently our recommended workflow (for CELLECT-LDSC). For the technical details on why HapMap3 SNPs are recommended and sufficient, see the supplementary material for the [S-LDSC paper](https://www.nature.com/articles/ng.3404) (Finucane, Nat. Gen 2015).

For CELLECT-MAGMA you do not have to restrict to HapMap3 SNPs, but I encourage you to check how robust your cell-type prioritization results is to the SNP filtering. And please share your results here (in a plot) if you get the time.

**Comment by pascaltimshel** [comment]
Hi @satzel , please let us know if your problem as been resolved. 
I will close the issue for now.

**Comment by rrydbirk** [comment]
I can see that a lot of people have this problem, going from chr. position to rsID, myself included. @satzel or @pascaltimshel, could you possibly include a short description of how you did this/best practice for this? I'm mostly working in R, and there it seems that no package actually handles this issue that well.

**Comment by satzel** [comment]
Hi @rrydbirk I also couldn't use R ( would have used biomaRt but I had thousands of IDs to convert and had trouble with it lately). I ended up using the command line version of VEP and annotated CHR ID pos with rsIDs. This is not a great solution cause you have to cut and paste the annotated IDs back to the GWAS summary. So I was not particularly happy about my solution. But at least it got me results. I think it would be great to see a best practice solution for this. Are people using PLINK maybe?

**Comment by rrydbirk** [comment]
Thanks for your input, @satzel. I've also seen people suggesting PLINK. 
My solution in R was to download dbSNP153 track from GenomeBrowser for the appropriate genome assembly, merge chr and end-position for SNP (since the two datasets I downloaded from the GWAS Atlas, https://atlas.ctglab.nl/, were annotated this way), and matched these with my GWAS data to retrieve rsIDs. 
This operation took around 15 min for my input ~17M SNPs which in the end translated to ~3M rsIDs. The merging took ~5 min and was the most time consuming operation besides downloading.
