### ISSUE TITLE
Exporting genes assigned to GWAS variants

### ISSUE THREAD

**Issue by DaianeH** [perslab/CELLECT#53]
Hi,

Would it be possible to export the list of genes assigned to 100kb around the GWAS variants according to expression specificity by CELLECT?

Many thanks,
Daiane.

**Comment by Tobi1kenobi** [comment]
Hi Daiane,

This can hopefully be bundled into a new feature release that was already being worked on. I would expect it to be ready within 2 weeks but I'll update this thread when it is.

Kind regards,
Tobi

**Comment by Tobi1kenobi** [comment]
Hi Daiane,

So this has been added now. If you go to the config file and set `KEEP_ANNOTS` to True, CELLECT-LDSC will also return in the output the SNP annotations. This includes the ES value assigned to each SNP for every cell-type in your dataset as well as the list of genes that overlap that each SNP, as you requested.

If you just want the mapping and do not wish to run CELLECT-LDSC in its entirety you can add `--until make-annot` to your snakemake command e.g.

`snakemake --use-conda -j 20 -s cellect-ldsc.snakefile --configfile example/config_example.yml -pr --until make_annot`

I hope that's helpful - let me know if you have an issues.

All the best,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi, thank you so much for implementing this.
So I include the following in my config file:

KEEP_ANNOTS:
   True

And then run CELLECT normally, but I can't find the annotation file with the genes in any directory. Where is this output supposed to be?

Many thanks,

**Comment by Tobi1kenobi** [comment]
Hi Daiaine,

If you've pulled the latest version of CELLECT, `KEEP_ANNOTS` should already be in your config file but yes you need to set it to `True`.

The annotation files are split by chromosome and saved in the `out` directory as annot.gz files. If you run the CELLECT-LDSC example they save here:
```CELLECT/CELLECT-EXAMPLE/CELLECT-LDSC/out/annots/mousebrain-test```

The genes overlapping each SNP are the last column in the file.

Kind regards,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi, what's the best way of updating CELLECT, would it be by cloning it again with

git clone --recurse-submodules https://github.com/perslab/CELLECT.git

or is there an option that doesn't require downloading all the data again?

Thanks,
Daiane.

**Comment by Tobi1kenobi** [comment]
Hi Daiane,

To update CELLECT enter the following commands within your CELLECT directory:
```
git pull # get the latest version from github
git submodule update --init --recursive # get the latest version of the ldsc submodule*
```

Best,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi, thanks!
So I don't know exactly why this happens, but with 
git submodule update --init --recursive
the data inside  data/ldsc/ is not downloaded correctly. When I installed CELLECT for the first time I ended up downloading it manually from the GitHub repository. When I run the 
git submodule update --init --recursive
command, the data downloaded ends up looking like this:

head data/ldsc/GRCh37-chr-sizes.txt
version https://git-lfs.github.com/spec/v1
oid sha256:1a24f93747225746064479ef80a54e8d98d946290c432125a5b1f1016d6d2b50
size 269

or 
 head data/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.8.bed
version https://git-lfs.github.com/spec/v1
oid sha256:ea74718d2a993970af088aa9ceff340c2d6ad6e5cad579d7c0bdd57a133fbe29
size 67646436

Do you know why that may be?

Many thanks again,

**Comment by Tobi1kenobi** [comment]
If you mean to say you simply cloned CELLECT and then manually downloaded LDSC too then yes you should reinstall from scratch following the instructions [here](https://github.com/perslab/CELLECT#installation). 

I believe your specific error arises when git lfs isn't downloading files correctly so make sure it is installed with `git lfs env`.

Best,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi, I had the following error when running the updated version of CELLECT:

--------
Loaded config file from --configfile argument
KeyError in line 61 of CELLECT/cellect-ldsc.snakefile:
'GENE_COORD_FILE'
  File "CELLECT/cellect-ldsc.snakefile", line 61, in <module>
--------

Line 61 says:
GENE_COORD_FILE = os.path.abspath(config['GENE_COORD_FILE'])

I wondered if it has something to do with this:
https://github.com/perslab/CELLECT/commit/ebca9f720177df82ad8d59e2ff119d3d93bb7798

and then replaced line
GENE_COORD_FILE = os.path.abspath(config['GENE_COORD_FILE'])
with
GENE_COORD_FILE =os.path.join(DATA_DIR,'gene_annotation.hsapiens_all_genes.GRCh37.ens_v91.LDSC_fmt.txt')
Then CELLECT run normally.

However, at the very end I got the following error:

--------
  input: ./CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/out/prioritization/arc_all__BMI_Yengo2018.cell_type_results.txt
    output: ./CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/results/prioritization.csv
    jobid: 1
    wildcards: BASE_OUTPUT_DIR=./CELLECT-LDSC-EXAMPLE/CELLECT-LDSC

INFO:parse_results:Compiling prioritization result files from 1 files
Traceback (most recent call last):
  File "/hpc/users/hemerd01/conda/envs/myenv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1618, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1626, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/parse_results.py", line 116, in <module>
    main(args.base_output_dir, logger)
  File "scripts/parse_results.py", line 39, in main
    prioritization_combined['specificity_id'] = specificity_id_annotation[0] #mousebrain
  File "/hpc/users/hemerd01/conda/envs/myenv/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/hpc/users/hemerd01/conda/envs/myenv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1618, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1626, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0
[Mon Jun  8 17:16:10 2020]
Error in rule parse_results:
    jobid: 1
    output: ./CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/results/prioritization.csv
    shell:
        python3 scripts/parse_results.py --base_output_dir ./CELLECT-LDSC-EXAMPLE/CELLECT-LDSC
--------

Do you know what can be causing this?

Thanks again,
Best,
Daiane.

**Comment by Tobi1kenobi** [comment]
Hi Daiane,

I would recommend reinstalling CELLECT. The file you corrected the path to does not exist in the [current version ](https://github.com/perslab/CELLECT/tree/master/data/ldsc) of CELLECT so your data directory hasn't updated properly.

Best,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi, that fixed.

But then now I seem to have another error, and since I can't find out why, am sending you the inputs (esmu, sum stats, and config files, here: https://drive.google.com/file/d/10Ix01x2WdIa87ajH1XKrq8kTupW_H9Dj/view?usp=sharing ). 

The error is in rule parse_results, so it seems that everything runs, but by the time of parsing CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/out/prioritization/arc_all__BMI_Yengo2018.cell_type_results.txt into CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/results/prioritization.csv, there's a KeyError: 0. Indeed, this happens:

(myenv) [hemerd01@loosr01-2 CELLECT]$ head CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/out/prioritization/arc_all__BMI_Yengo2018.cell_type_results.txt
Name	Coefficient	Coefficient_std_error	Coefficient_P_value

Meaning the file to be parsed with results is actually empty.

Could you please try to run it on your end to see if the same happens?
Many many thanks.

**Comment by Tobi1kenobi** [comment]
Hi Daiane,

I just ran CELLECT now on the specificity input you provided and it worked fine with all the relevant information parsed to `prioritization.csv`.

Based on the error you provided it is really difficult for me to know what went wrong, I would advise checking the logs here `CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/logs`.

Note: I didn't use the config file or sumstats file you provided as I already had BMI Yengo 2018 downloaded and munged (as per the CELLECT-LDSC tutorial) and for the config I used the template provided (I wanted to run our example `mousebrain-test` in parallel as a control). 

I can't say what is failing in your instance but I would advise trying to run the [example](https://github.com/perslab/CELLECT/wiki/CELLECT-LDSC-Tutorial) from a fresh install before trying anything else - as there doesn't seem to be anything wrong with your data. If the example data works, add your data on in the same config file template e.g.

```
SPECIFICITY_INPUT:
  - id: mousebrain-test
    path: example/mousebrain-test.csv.gz # this test file contains 2 annotations
  - id: tabula_muris-test
    path: example/tabula_muris-test.csv # this test file contains 5 annotations
  - id: arc_all
    path: daiane_data/arc_allclusters_cellect_ensembl.esmu.csv.gz
```

Best,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi, sorry for yet another message here, but I had the exact same error in parsing when running CELLECT using your example config file ( https://github.com/perslab/CELLECT/blob/master/example/config_example.yml )

(I only commented
 # - id: EA3_Lee2018
 #  path: example/EA3_Lee2018.sumstats.gz )

I was thinking, I downloaded and munged the BMI Yengo 2018 (as per the CELLECT-LDSC tutorial), but could you perhaps send me your sumstats file so I can run and test if that's what went wrong and is causing an error?

Many thanks,

**Comment by Tobi1kenobi** [comment]
I just tried the example now with the sumstats you uploaded and it worked. I can only assume it's your installation if you used the exact config file provided and followed the munging tutorial.

Can you send the contents of your log file that I mentioned before, this file in particular should hopefully reveal the error:
`log.prioritize_annotations.mousebrain-test.BMI_Yengo2018.txt`

Best,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi,

Here's the log file for the job we're testing with my dataset (for some reason, no log file is written when I run CELLECT on the example config file):

[log.prioritize_annotations.arc_all.BMI_Yengo2018.txt](https://github.com/perslab/CELLECT/files/4789035/log.prioritize_annotations.arc_all.BMI_Yengo2018.txt)

Thanks,
Daiane.

**Comment by Tobi1kenobi** [comment]
Hmm well that confirms that LDSC isn't working properly. For the CELLECT example config can you send the last log file to be produced?

Best,
Tobi

**Comment by DaianeH** [comment]
Sure, here:

[log.prioritize_annotations.mousebrain-test.BMI_Yengo2018.txt](https://github.com/perslab/CELLECT/files/4793410/log.prioritize_annotations.mousebrain-test.BMI_Yengo2018.txt)

**Comment by DaianeH** [comment]
Hi Tobi,

It's solved! It worked, with annotations and genes and everything, thank you so much! Just one observation:

So because apparently I'm having problems with git-lfs, I asked our HPC admin to download CELLECT herself. She managed to download CELLECT with all files within CELLECT/data/ldsc. However, no files were downloaded in CELLECT/ldsc (like the scripts for munging, or make annotations, etc - the directory was empty). I wonder if it's because when I checked here: https://github.com/perslab/CELLECT the name of directory ldsc is now "ldsc @ d869cfd", and maybe that's because the download of files from this directory is not working properly?
Anyway, I copied all the files that I know should be inside CELLECT/ldsc from a previous installation of CELLECT, and then run it and it worked.

Many thanks again,
Daiane.

**Comment by Tobi1kenobi** [comment]
Good to hear! And interesting that git lfs seems to be the issue - that should be useful if anyone else has the same error in the future.

RE: Missing 'ldsc' directory. The directory name has always been `ldsc @ {hash}` - this is because it's a git [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) rather than being just a normal directory. Given the scenario you described I think it is likely your HPC admin installed CELLECT with `git clone git@github.com:perslab/CELLECT.git` rather than the correct command `git clone --recurse-submodules https://github.com/perslab/CELLECT.git`. Installing with the former command would install everything correctly but leave the `ldsc` directory empty as you mentioned.

Anyway I'm glad it's all working now - I hope you find CELLECT-LDSC and CELLECT-MAGMA useful!

Best,
Tobi
