### ISSUE TITLE
ValueError: Index gene invalid

### ISSUE THREAD

**Issue by rrydbirk** [perslab/CELLECT#54]
I get this error. My input is Ensembl gene IDs, and I've sorted my data to only include genes in ~/CELLECT/data/shared/gene_coordinates.GRCh37.ensembl_v91.txt. Can you help me?

(base) ➜  CELLECT git:(master) ✗ snakemake --use-conda -j 20 -s cellect-ldsc.snakefile --configfile example/config.yml
Loaded config file from --configfile argument
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 20
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        22      10
        1       all
        22      compute_LD_scores
        22      compute_LD_scores_all_genes
        22      find_overlaps
        1       format_genes
        1       make_all_genes_background
        22      make_annot
        22      make_annot_all_genes
        1       make_cts_file
        1       parse_results
        1       prioritize_annotations
        138

[Wed Jun  3 04:51:52 2020]
rule make_all_genes_background:
    input: /d0/home/rasmusr/CELLEX/Cellex.results.csv.gz
    output: x/CELLECT-LDSC/precomputation/y/all_genes.y.csv
    jobid: 114
    wildcards: BASE_OUTPUT_DIR=x/CELLECT-LDSC, run_prefix=y

[Wed Jun  3 04:51:52 2020]
rule format_genes:
    input: /d0/home/rasmusr/CELLECT/data/shared/gene_coordinates.GRCh37.ensembl_v91.txt, /d0/home/rasmusr/CELLECT/data/ldsc/GRCh37-chr-sizes.txt
    output: x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.1.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.2.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.3.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.4.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.5.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.6.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.7.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.8.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.9.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.10.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.11.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.12.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.13.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.14.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.15.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.16.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.17.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.18.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.19.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.20.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.21.bed, x/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.22.bed
    log: x/CELLECT-LDSC/logs/log.format_genes_snake.txt
    jobid: 137
    wildcards: BASE_OUTPUT_DIR=x/CELLECT-LDSC

Activating conda environment: /d0/home/rasmusr/CELLECT/.snakemake/conda/acc25b11
Activating conda environment: /d0/home/rasmusr/CELLECT/.snakemake/conda/acc25b11
Traceback (most recent call last):
  File "/d0/home/rasmusr/CELLECT/.snakemake/scripts/tmpowmqtng4.make_all_genes_snake.py", line 29, in <module>
    make_all_genes(specificity_matrix_file, specificity_matrix_name, output_dir)
  File "/d0/home/rasmusr/CELLECT/.snakemake/scripts/tmpowmqtng4.make_all_genes_snake.py", line 12, in make_all_genes
    specificity_df = pd.read_csv(specificity_matrix_file, index_col='gene')
  File "/d0/home/rasmusr/CELLECT/.snakemake/conda/acc25b11/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/d0/home/rasmusr/CELLECT/.snakemake/conda/acc25b11/lib/python3.6/site-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/d0/home/rasmusr/CELLECT/.snakemake/conda/acc25b11/lib/python3.6/site-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/d0/home/rasmusr/CELLECT/.snakemake/conda/acc25b11/lib/python3.6/site-packages/pandas/io/parsers.py", line 2069, in read
    index, names = self._make_index(data, alldata, names)
  File "/d0/home/rasmusr/CELLECT/.snakemake/conda/acc25b11/lib/python3.6/site-packages/pandas/io/parsers.py", line 1541, in _make_index
    index = self._get_simple_index(alldata, columns)
  File "/d0/home/rasmusr/CELLECT/.snakemake/conda/acc25b11/lib/python3.6/site-packages/pandas/io/parsers.py", line 1574, in _get_simple_index
    i = ix(idx)
  File "/d0/home/rasmusr/CELLECT/.snakemake/conda/acc25b11/lib/python3.6/site-packages/pandas/io/parsers.py", line 1569, in ix
    raise ValueError('Index %s invalid' % col)
ValueError: Index gene invalid
[Wed Jun  3 04:51:55 2020]
Error in rule make_all_genes_background:
    jobid: 114
    output: x/CELLECT-LDSC/precomputation/y/all_genes.y.csv
    conda-env: /d0/home/rasmusr/CELLECT/.snakemake/conda/acc25b11

[Wed Jun  3 04:51:56 2020]
Finished job 137.
1 of 138 steps (0.72%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /d0/home/rasmusr/CELLECT/.snakemake/log/2020-06-03T045145.257289.snakemake.log

(base) ➜  CELLECT git:(master) ✗ conda list
# packages in environment at /home/rasmusr/bin/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
_libgcc_mutex             0.1                        main
adjusttext                0.7.3                    pypi_0    pypi
aioeasywebdav             2.4.0                 py37_1000    conda-forge
aiohttp                   3.6.2            py37h516909a_0    conda-forge
alabaster                 0.7.12                   py37_0
anaconda                  2019.10                  py37_0
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.7                    py37_0
anaconda-project          0.8.3                      py_0
aniso8601                 8.0.0                    pypi_0    pypi
annoy                     1.16.3                   pypi_0    pypi
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                1.0.1                    py37_0
astroid                   2.3.1                    py37_0
astropy                   3.2.2            py37h7b6447c_0
async-timeout             3.0.1                   py_1000    conda-forge
atomicwrites              1.3.0                    py37_1
attrs                     19.2.0                     py_0
babel                     2.7.0                      py_0
backcall                  0.1.0                    py37_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.5                        py_2
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.1.7            py37h8f50634_1    conda-forge
beautifulsoup4            4.8.0                    py37_0
bitarray                  1.0.1            py37h7b6447c_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blosc                     1.16.3               hd408876_0
bokeh                     1.3.4                    py37_0
boto                      2.49.0                   py37_0
boto3                     1.7.84                   pypi_0    pypi
botocore                  1.10.84                  pypi_0    pypi
bottleneck                1.2.1            py37h035aef0_1
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2019.8.28                     0
cachetools                4.1.0                      py_1    conda-forge
cairo                     1.14.12              h8948797_3
cellex                    1.1.1                    pypi_0    pypi
cellphonedb               2.1.2                    pypi_0    pypi
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.12.3           py37h2e261b9_0
chardet                   3.0.4                 py37_1003
click                     6.7                      pypi_0    pypi
cloudpickle               1.2.2                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.4.1                    py37_0
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-build               3.18.9                   py37_3
conda-env                 2.6.0                         1
conda-package-handling    1.6.0            py37h7b6447c_0
conda-verify              3.4.2                      py_1
configargparse            1.2.3              pyh9f0ad1d_0    conda-forge
contextlib2               0.6.0                      py_0
cryptography              2.7              py37h1ba5d50_0
curl                      7.65.3               hbc83047_0
cycler                    0.10.0                   py37_0
cython                    0.29.13          py37he6710b0_0
cytoolz                   0.10.0           py37h7b6447c_0
dask                      2.5.2                      py_0
dask-core                 2.5.2                      py_0
datrie                    0.8.2            py37h8f50634_0    conda-forge
dbus                      1.13.6               h746ee38_0
decorator                 4.4.0                    py37_1
defusedxml                0.6.0                      py_0
descartes                 1.1.0                    pypi_0    pypi
distributed               2.5.2                      py_0
docutils                  0.15.2                   py37_0
dropbox                   9.4.0                      py_0    conda-forge
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                    py37_0
expat                     2.2.6                he6710b0_0
fastcache                 1.1.0            py37h7b6447c_0
fbpca                     1.0                      pypi_0    pypi
filechunkio               1.8                        py_2    conda-forge
filelock                  3.0.12                     py_0
flask                     1.0.4                    pypi_0    pypi
flask-restful             0.3.8                    pypi_0    pypi
flask-testing             0.7.1                    pypi_0    pypi
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_1
fribidi                   1.0.5                h7b6447c_0
fsspec                    0.5.2                      py_0
ftputil                   3.4                        py_0    conda-forge
future                    0.17.1                   py37_0
geosketch                 0.3                      pypi_0    pypi
get_terminal_size         1.0.0                haa9412d_0
gevent                    1.4.0            py37h7b6447c_0
gitdb                     4.0.5                      py_0    conda-forge
gitpython                 3.1.2                      py_0    conda-forge
glib                      2.56.2               hd408876_0
glob2                     0.7                        py_0
gmp                       6.1.2                h6c8ec71_1
gmpy2                     2.0.8            py37h10f8cd9_2
google-api-core           1.17.0           py37hc8dfbb8_0    conda-forge
google-auth               1.14.3             pyh9f0ad1d_0    conda-forge
google-cloud-core         1.3.0                      py_0    conda-forge
google-cloud-storage      1.28.1             pyh9f0ad1d_0    conda-forge
google-resumable-media    0.5.0                      py_1    conda-forge
googleapis-common-protos  1.51.0           py37hc8dfbb8_2    conda-forge
graphite2                 1.3.13               h23475e2_0
graphviz                  2.40.1               h21bd128_2
greenlet                  0.4.15           py37h7b6447c_0
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
h5py                      2.9.0            py37h7918eee_0
harfbuzz                  1.8.8                hffaf4a1_0
hdf5                      1.10.4               hb1b8bf9_0
heapdict                  1.0.1                      py_0
html5lib                  1.0.1                    py37_0
icu                       58.2                 h9c2bf20_1
idna                      2.7                      pypi_0    pypi
imageio                   2.6.0                    py37_0
imagesize                 1.1.0                    py37_0
importlib_metadata        0.23                     py37_0
intel-openmp              2019.4                      243
ipykernel                 5.1.2            py37h39e3cac_0
ipython                   7.8.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py37_0
itsdangerous              1.1.0                    py37_0
jbig                      2.1                  hdba287a_0
jdcal                     1.4.1                      py_0
jedi                      0.15.1                   py37_0
jeepney                   0.4.1                      py_0
jinja2                    2.10.3                     py_0
jmespath                  0.9.5                    pypi_0    pypi
joblib                    0.13.2                   py37_0
jpeg                      9b                   h024ee3a_2
json5                     0.8.5                      py_0
jsonschema                3.0.2                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.3                    py37_1
jupyter_console           6.0.0                    py37_0
jupyter_core              4.5.0                      py_0
jupyterlab                1.1.4              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0
keyring                   18.0.0                   py37_0
kiwisolver                1.1.0            py37he6710b0_0
krb5                      1.16.1               h173b8e3_7
lazy-object-proxy         1.4.2            py37h7b6447c_0
libarchive                3.3.3                h5d8350f_5
libcurl                   7.65.3               h20c2e04_0
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
liblief                   0.9.0                h7725739_2
libpng                    1.6.37               hbc83047_0
libprotobuf               3.12.1               h8b12597_0    conda-forge
libsodium                 1.0.16               h1bed415_0
libssh2                   1.8.2                h1ba5d50_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.0.10               h2733197_2
libtool                   2.4.6                h7b6447c_5
libuuid                   1.0.3                h1bed415_2
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.9                hea5a465_1
libxslt                   1.1.33               h7d1a2b0_0
llvmlite                  0.29.0           py37hd408876_0
locket                    0.2.0                    py37_1
loompy                    3.0.6                    pypi_0    pypi
lxml                      4.4.1            py37hefd8a0e_0
lz4-c                     1.8.1.2              h14c3975_0
lzo                       2.10                 h49e0be7_2
markupsafe                1.1.1            py37h7b6447c_0
matplotlib                3.1.1            py37h5429711_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4            py37h7b6447c_0
mizani                    0.6.0                    pypi_0    pypi
mkl                       2019.4                      243
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.0.14           py37ha843d7b_0
mkl_random                1.1.0            py37hd6b4f25_0
mock                      3.0.5                    py37_0
more-itertools            7.2.0                    py37_0
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.1                hdf1c602_3
mpmath                    1.1.0                    py37_0
msgpack-python            0.6.1            py37hfd86e86_1
multidict                 4.7.5            py37h8f50634_1    conda-forge
multipledispatch          0.6.0                    py37_0
navigator-updater         0.2.1                    py37_0
nbconvert                 5.6.0                    py37_1
nbformat                  4.4.0                    py37_0
ncurses                   6.1                  he6710b0_1
networkx                  2.3                        py_0
nltk                      3.4.5                    py37_0
nose                      1.3.7                    py37_2
notebook                  6.0.1                    py37_0
numba                     0.45.1           py37h962f231_0
numexpr                   2.7.0            py37h9e4a6bb_0
numpy                     1.17.2           py37haad9e8e_0
numpy-base                1.17.2           py37hde5b4d6_0
numpy-groupies            0+unknown                pypi_0    pypi
numpydoc                  0.9.1                      py_0
olefile                   0.46                     py37_0
openpyxl                  3.0.0                      py_0
openssl                   1.1.1d               h7b6447c_2
packaging                 19.2                       py_0
palettable                3.3.0                    pypi_0    pypi
pandas                    1.0.3                    pypi_0    pypi
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
pango                     1.42.4               h049681c_0
paramiko                  2.7.1                    py37_0    conda-forge
parso                     0.5.1                      py_0
partd                     1.0.0                      py_0
patchelf                  0.9                  he6710b0_3
path.py                   12.0.1                     py_0
pathlib2                  2.3.5                    py37_0
patsy                     0.5.1                    py37_0
pcre                      8.43                 he6710b0_0
pep8                      1.7.1                    py37_0
pexpect                   4.7.0                    py37_0
pickleshare               0.7.5                    py37_0
pika                      0.12.0                   pypi_0    pypi
pillow                    6.2.0            py37h34e0f95_0
pip                       19.2.3                   py37_0
pixman                    0.38.0               h7b6447c_0
pkginfo                   1.5.0.1                  py37_0
plotnine                  0.6.0                    pypi_0    pypi
pluggy                    0.13.0                   py37_0
ply                       3.11                     py37_0
prettytable               0.7.2                      py_3    conda-forge
prometheus_client         0.7.1                      py_0
prompt_toolkit            2.0.10                     py_0
protobuf                  3.12.1           py37h3340039_0    conda-forge
psutil                    5.6.3            py37h7b6447c_0
ptyprocess                0.6.0                    py37_0
py                        1.8.0                    py37_0
py-lief                   0.9.0            py37h7725739_2
pyarrow                   0.17.1                   pypi_0    pypi
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37h14c3975_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37h14c3975_9
pycurl                    7.43.0.3         py37h1ba5d50_0
pyflakes                  2.1.1                    py37_0
pygments                  2.4.2                      py_0
pygraphviz                1.3              py37h14c3975_1
pylint                    2.4.2                    py37_0
pynacl                    1.3.0           py37h516909a_1001    conda-forge
pyodbc                    4.0.27           py37he6710b0_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.2                      py_0
pyqt                      5.9.2            py37h05f1152_2
pyreadr                   0.2.9                    pypi_0    pypi
pyrsistent                0.15.4           py37h7b6447c_0
pysam                     0.15.4                   pypi_0    pypi
pysftp                    0.2.9                      py_1    conda-forge
pysocks                   1.7.1                    py37_0
pytables                  3.5.2            py37h71ec239_1
pytest                    5.2.1                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.5.0                    py37_0
pytest-doctestplus        0.4.0                      py_0
pytest-openfiles          0.4.0                      py_0
pytest-remotedata         0.3.2                    py37_0
python                    3.7.4                h265db76_1
python-dateutil           2.8.0                    py37_0
python-irodsclient        0.8.2                      py_0    conda-forge
python-libarchive-c       2.8                     py37_13
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0
pywavelets                1.0.3            py37hdd07704_1
pyyaml                    5.1.2            py37h7b6447c_0
pyzmq                     18.1.0           py37he6710b0_0
qt                        5.9.7                h5867ecd_1
qtawesome                 0.6.0                      py_0
qtconsole                 4.5.5                      py_0
qtpy                      1.9.0                      py_0
ratelimiter               1.2.0                 py37_1000    conda-forge
readline                  7.0                  h7b6447c_5
requests                  2.19.1                   pypi_0    pypi
ripgrep                   0.10.0               hc07d326_0
rope                      0.14.0                     py_0
rpy2                      3.0.5                    pypi_0    pypi
rsa                       4.0                        py_0    conda-forge
ruamel_yaml               0.15.46          py37h14c3975_0
s3transfer                0.1.13                   pypi_0    pypi
scikit-image              0.15.0           py37he6710b0_0
scikit-learn              0.21.3           py37hd81dba3_0
scipy                     1.3.1            py37h7c811a0_0
scrublet                  0.2.1                    pypi_0    pypi
seaborn                   0.9.0                    py37_0
secretstorage             3.1.1                    py37_0
send2trash                1.5.0                    py37_0
setuptools                41.4.0                   py37_0
setuptools-scm            4.1.1                    pypi_0    pypi
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37hf484d3e_0
six                       1.12.0                   py37_0
smmap                     3.0.4              pyh9f0ad1d_0    conda-forge
snakemake                 5.4.5                         0    bioconda
snakemake-minimal         5.4.5                      py_0    bioconda
snappy                    1.1.7                hbae5bb6_3
snowballstemmer           2.0.0                      py_0
sortedcollections         1.1.2                    py37_0
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.9.3                    py37_0
sphinx                    2.2.0                      py_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
sphinxcontrib-websupport  1.1.2                      py_0
spyder                    3.3.6                    py37_0
spyder-kernels            0.5.2                    py37_0
sqlalchemy                1.3.9            py37h7b6447c_0
sqlite                    3.30.0               h7b6447c_0
statsmodels               0.10.1           py37hdd07704_0
sympy                     1.4                      py37_0
tbb                       2019.4               hfd86e86_0
tblib                     1.4.0                      py_0
terminado                 0.8.2                    py37_0
testpath                  0.4.2                    py37_0
tk                        8.6.8                hbc83047_0
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37h7b6447c_0
tqdm                      4.32.2                   pypi_0    pypi
traitlets                 4.3.3                    py37_0
tzlocal                   2.1                      pypi_0    pypi
umap-learn                0.3.10                   pypi_0    pypi
unicodecsv                0.14.1                   py37_0
unixodbc                  2.3.7                h14c3975_0
urllib3                   1.23                     pypi_0    pypi
velocyto                  0.17.17                  pypi_0    pypi
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.16.0                     py_0
wheel                     0.33.6                   py37_0
widgetsnbextension        3.5.1                    py37_0
wrapt                     1.11.2           py37h7b6447c_0
wurlitzer                 1.0.3                    py37_0
xlrd                      1.2.0                    py37_0
xlsxwriter                1.2.1                      py_0
xlwt                      1.3.0                    py37_0
xmlrunner                 1.7.7                      py_0    conda-forge
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
yarl                      1.3.0           py37h516909a_1000    conda-forge
zeromq                    4.3.1                he6710b0_3
zict                      1.0.0                      py_0
zipp                      0.6.0                      py_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0

**Comment by Tobi1kenobi** [comment]
Hi Rasmus,

Would you be able to share your specificity matrix file? It seems that Pandas is having issues reading the gene column.

Also as an aside, CELLECT only requires Snakemake in your environment - all of the scripts have conda environments created for them behind the scenes with locked package versions. In other words, your package environment can almost certainly be ruled out as the issue.

Best,
Tobi

**Comment by Tobi1kenobi** [comment]
I just noticed it looks like you used CELLEX to generate your specificity matrix file - if that's the case you shouldn't need any post-processing (i.e. sorting or filtering). CELLEX Ensembl human output should work directly with CELLECT.

**Comment by tstannius** [comment]
Perhaps related to: https://github.com/perslab/CELLEX/issues/24 ?

Although Rasmus did find a solution.

**Comment by rrydbirk** [comment]
@Tobi1kenobi Indeed, I used CELLEX. However, I thought the error was due to me inputting genes that weren't in the CELLECT annotation file, but that wasn't the case.

@tstannius Yes, no problems with CELLEX anymore, and I reran that part with human Ensembl IDs (instead of gene symbols which I initially used).

I've shared my data here temporarily (I know it's not .csv.gz): https://www.dropbox.com/s/6zc5dqmps7xxkoe/Cellex.results.zip?dl=0

**Comment by Tobi1kenobi** [comment]
Hi Rasmus,

So I reproduced the error locally. The first column of your specificity matrix needs to be named `gene` (see our example input [here](https://github.com/perslab/CELLECT/wiki/Input-&-Output#specificity_input).

There seems to be a bit of confusion as the documentation states the index column can be named anything at all but clearly this is not the case - I'll change the documentation now and try to make it clearer for other users.

The rest of the pipeline should work now but let us know if that isn't the case.

Best,
Tobi

**Comment by rrydbirk** [comment]
Hi Tobi
Thanks for your help, now this part ran W/O problems.

However, I now have another problem (and one question), I don't know if I should make another issue. 
I was under the impression that I would be able to run CELLECT-MAGMA directly afterwards. Nevertheless, this is what I get:
(base) ➜  CELLECT git:(master) ✗ snakemake --use-conda -j -s cellect-magma.snakefile --configfile example/config.yml
Loaded config file from --configfile argument
Building DAG of jobs...
MissingInputException in line 207 of /d0/home/rasmusr/CELLECT/cellect-magma.snakefile:
Missing input files for rule get_uncorrected_pvals:
Nalls2019/CELLECT-MAGMA/precomputation/Nalls2019.sumstats

First row of my sumstats file is this:
SNP	A1	A2	Z	N	SE	PVAL
rs6678176	T	C	1.31502946515	378755.399715	0.0245	0.1885

Can you see what's wrong here?

And now to the question: How come my N for this SNP is 378755.399715, when my input summary statistics file looks like this (before munging):
sumstat[sumstat$SNP == "rs6678176",]
# A tibble: 1 x 10
  SNP       A1    A2     freq      b     se     p N_cases N_controls      N
1 rs6678176 T     C     0.290 0.0322 0.0245 0.188   26421     442271 468692

I'm curious why these Ns are so different.

BR

Rasmus

**Comment by Tobi1kenobi** [comment]
Hi Rasmus,

Unfortunately I have not worked much on the development of CELLECT-MAGMA nor am I well-versed in the munging step so am probably in a poor position to answer that particular question.

If you could make another issue that would be great - then hopefully a developer more familiar with your question will see it and additionally the issue will be logged on GitHub distinctly separate from this one.

Best,
Tobi
