### ISSUE TITLE
Point file error

### ISSUE THREAD

**Issue by verdurin** [perslab/CELLECT#57]
I see the following error when cloning the repo:
```
Pointer file error: Unable to parse pointer at: "example/mousebrain-test.csv.gz"
```
with
```
git clone --recurse-submodules https://github.com/perslab/CELLECT.git
```
`git-lfs` is installed.

**Comment by pvtodorov** [comment]
Hi! what directory are you running the script in? what happens when you `ls example` in that directory?

**Comment by verdurin** [comment]
@pvtodorov Wonder whether this was a transient problem at the Github end? 
I'm actually running this inside a Singularity container and trying it again just now I can't see the error.

**Comment by Tobi1kenobi** [comment]
I believe this error is a result of the [.gitattributes](https://github.com/perslab/CELLECT/blob/master/.gitattributes) file specifying all files with a `.gz` extension should be handled by git lfs. I also see this error when I do a fresh clone. You can rest assured, @verdurin, it shouldn't affect the functionality of CELLECT.

The uncompressed file isn't particularly large so I'll replace it now as a hotfix.
