### ISSUE TITLE
Distance of genes assigned to GWAS variants

### ISSUE THREAD

**Issue by DaianeH** [perslab/CELLECT#59]
Hi,

Thanks for implementing the KEEP_ANNOTS functionality that allows to export the annotations showing which genes were assigned to GWAS variants.

If I understood correctly from the paper, the gene assigned to each variant is the one with highest expression specificity (ES, from CELLEX) within a 100KB window around the variant. Is that correct?

I was checking the results of my scRNA-seq dataset on Yengo et al data, and for example the BMI-associated SNP rs761423 in the .annot files has 5 genes assigned to it. I retrieved these genes start and end from Ensemble's database and used the command "closest" from bedtools to check the distance between these genes and rs761423. This is the result:

chr	snp_start	snp_end	snp	dataset	chr	gene_start	gene_end	gene_name	gene_id	distance_snp_to_gene_bp
chr1    17301672        17301672        rs761423        1       chr1    19665267        19812066        CAPZB   ENSG00000077549 2363595
chr1    17301672        17301672        rs761423        2       chr1    19967048        19984945        NBL1    ENSG00000158747 2665376
chr1    17301672        17301672        rs761423        3       chr1    19991780        20006055        HTR6    ENSG00000158748 2690108
chr1    17301672        17301672        rs761423        4       chr1    19923477        19956314        MINOS1  ENSG00000173436 2621805

It seems the genes assigned to this SNP are >2K kb away. Is this correct, or something wrong happened?

Thanks,

**Comment by Tobi1kenobi** [comment]
Hi again Daiane,

I don't have time to look into this at the moment but I can get back to you hopefully sometime next week with an explanation.

All the best,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi, I was wondering did you perhaps have the time to take a look at this issue?

thanks,
Daiane.

**Comment by Tobi1kenobi** [comment]
Hey Daiane,

Sorry for leaving this longer than expected - other things popped up and it kept getting pushed further and further down my to-do list. This is indeed a bug however fortunately the error seems to be with the way I've printed the genes when I implemented the KEEP_ANNOTS change rather than CELLECT itself. In other words, all your results will still be valid it's just the genes returned by KEEP_ANNOTS are incorrect.

Thank you for pointing this out! I'm annoyed at myself for missing it but am working on a fix now and will update ASAP.

Tobi

**Comment by Tobi1kenobi** [comment]
Hey Daiane,

This should be fixed now, for peace of mind I checked the variant you mentioned and it now lists:
rs761423        33.996868       17301672        0.8773710147510557      0.010583254938852305    ENSG00000058453;ENSG00000117115;ENSG00000117118;ENSG00000117122;ENSG00000159363

I went to the Ensembl genome browser and looked at the region [chr1:17293256-17493256](http://grch37.ensembl.org/Homo_sapiens/Location/View?db=core;r=1:17293256-17493256) which overlaps 5 protein-coding genes. The 5 genes listed above.

Thanks again for pointing this out, mistakes can sometimes creep in unexpectedly and it's always nice to be alerted to them

Kind regards,
Tobi
