### ISSUE TITLE
Python conflict

### ISSUE THREAD

**Issue by DaianeH** [perslab/CELLECT#62]
Hi,

I've been using CELLECT for several months now and never had an issue with Python versions (I use python/3.7.3 - since python 3 is needed to load the modules CELLECT uses), but out of a sudden whenever running the snakemake --use-conda etc command, it started complaining about the syntax of commands on ldsc scripts that are in python 2 (print command for instance changes between python 2 and 3, in version 3 parenthesis should be added). I've been manually editing the ldsc scripts every single time it complains about these syntax differences from python 2 to 3 issues, but it's getting exhausting and still not working.

I'm wondering, am I the only one having these issues, and why would that be? - and also what to do?

Thanks,

**Comment by Tobi1kenobi** [comment]
Hey Daiane,

Glad you've been using CELLECT and it's been helpful for your research! This is very odd - how long has this happened for? Can you think of any thing different about your system maybe?

Firstly, if you can, reinstall CELLECT from scratch - I don't know which modifications you've made to the LDSC scripts so it's easier to just start afresh. Plus this will delete all your existing built-in CELLECT conda envs and will give some sort of indication as to whether it is your CELLECT installation or your system.

If the problem persists after reinstalling, come back and maybe post the log so I can see if the environments are being activated at all or not.

Kind regards,
Tobi

**Comment by Tobi1kenobi** [comment]
Hey Daiane,

Glad you've been using CELLECT and it's been helpful for your research! This is very odd - how long has this happened for? Can you think of any thing different about your system maybe?

Firstly, if you can, reinstall CELLECT from scratch - I don't know which modifications you've made to the LDSC scripts so it's easier to just start afresh. Plus this will delete all your existing built-in CELLECT conda envs and will give some sort of indication as to whether it is your CELLECT installation or your system.

If the problem persists after reinstalling, come back and maybe post the log so I can see if the environments are being activated at all or not.

Kind regards,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi,

I'm installing everything again, including installing snakemake via conda. The only thing is that I forgot how I had created my environment the previous time I installed, so I'll need your guidance here.

In the tutorial it says:

"All you need to do is to install miniconda (if conda is not already present on your system) and then install snakemake:
conda install -c bioconda -c conda-forge snakemake=5.4.5"

I loaded the module anaconda3 on the HPC and run conda install but got the error:

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /hpc/packages/minerva-centos7/anaconda3/2018.12

So I need to create the environment first. How do I create the environment again?

If I do for example:

$ conda env create --name cellect

I get:
8.3.0
SpecNotFound: Invalid name, try the format: user/package

So what is missing?

**Comment by Tobi1kenobi** [comment]
I think the command is simply `conda create`. So the following should work:
` conda create -c conda-forge -c bioconda -n cellect snakemake=5.4.5`

Using the conda installed on a HPC can sometimes be an issue if it's not set-up to let you create your own conda environments but hopefully yours is. Let me know how it goes.

Best,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi, Installation worked now and I'm in the new environment. But when I run CELLECT, the python conflict started all over again, with the first error being:

$ head  CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/logs/log.compute_LD_scores.all_genes_in_dataset.adipo.19.txt
  File "/sc/arion/projects/loosr01a/daiane/software/CELLECT_new2/CELLECT/ldsc/ldsc.py", line 94
    print msg
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(msg)?


Sending you the complete .log file attached.

Thanks for your help,
Daiane.

[2020-10-07T101651.340452.snakemake.log](https://github.com/perslab/CELLECT/files/5341534/2020-10-07T101651.340452.snakemake.log)

**Comment by Tobi1kenobi** [comment]
Thanks for the log - that's very helpful. It's strange that it is activating the conda environment but python 2.7 isn't working. Hopefully it's something specific to your HPC that can be worked around.

Can you try entering these commands:
```conda activate /sc/arion/projects/loosr01a/daiane/software/CELLECT_new2/CELLECT/.snakemake/conda/24614dfe
python```

And tell me if it launches a python 2.7 or python 3 console?

Best,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi, this happens:

$ python
Python 3.7.3 (default, Mar 28 2019, 12:17:05)
[GCC 8.3.0] on linux

**Comment by Tobi1kenobi** [comment]
OK that explains the issue. Can you now type in
```
which python
```
To confirm it's not the conda environment that is the problem.

**Comment by DaianeH** [comment]
No, it's not the conda environment:

$ which python
/hpc/packages/minerva-centos7/python/3.7.3/bin/python

But why isn't the python 2 from conda environment running, then?

**Comment by Tobi1kenobi** [comment]
I'm not exactly sure, it must be something specific to your HPC set-up. I can try dig into this and get back to you or you could ask the systems manager of your HPC and get back to me as they will know much better than I do your specific set-up.

Anything you find will be helpful to me as I'd like to change CELLECT to circumvent this, if possible.

Kind regards,
Tobi

**Comment by DaianeH** [comment]
Hi Tobi,

It worked again when I did ml purge, deleted the .snakemake folder, uninstalled and reinstalled miniconda3, and then went on to create and activate a new environment with snakemake.

But now I'm having another error. At the very last rule:


[Fri Oct  9 12:40:14 2020]
rule parse_results:
    input: CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/out/prioritization/adipo__yengo.cell_type_results.txt
    output: CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/results/prioritization.csv
    jobid: 1
    wildcards: BASE_OUTPUT_DIR=CELLECT-LDSC-EXAMPLE/CELLECT-LDSC

INFO:parse_results:Compiling prioritization result files from 4 files
Traceback (most recent call last):
  File "/hpc/users/hemerd01/conda/envs/cellect2/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/parse_results.py", line 132, in <module>
    main(args.base_output_dir, logger)
  File "scripts/parse_results.py", line 40, in main
    prioritization_combined['specificity_id'] = specificity_id_annotation[0] #mousebrain
  File "/hpc/users/hemerd01/conda/envs/cellect2/lib/python3.8/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/hpc/users/hemerd01/conda/envs/cellect2/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 0
[Fri Oct  9 12:40:15 2020]
Error in rule parse_results:
    jobid: 1
    output: CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/results/prioritization.csv
    shell:
        python3 scripts/parse_results.py --base_output_dir CELLECT-LDSC-EXAMPLE/CELLECT-LDSC

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message


That happens because file CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/out/prioritization/adipo__yengo.cell_type_results.txt that is supposed to be parsed, is empty. I can't however find out why it's empty. Could you please help me on this? Sending the log from the attempt with Yengo summary statistics and the example mouse brain dataset.

[2020-10-09T123928.830147.snakemake.log](https://github.com/perslab/CELLECT/files/5356326/2020-10-09T123928.830147.snakemake.log)


Many thanks,

**Comment by Tobi1kenobi** [comment]
Hey Daiane,

Could this be related to the same error you had back in [June](https://github.com/perslab/CELLECT/issues/53#issuecomment-642706686)? If it is different I think what I suggested back there should still be useful in debugging - run CELLECT with `--no-temp` and compare the files you produce at each stage to the example files I linked in that issue.

I also realised your conda issue is something that has been flagged before #44. Really annoying and I hope I can find a long-term solution soon.

Tobi

**Comment by DaianeH** [comment]
Hi Tobi,

I'm running with the example files and having the same error.

The error in log.prioritize_annotations.mousebrain-test.yengo.txt (attached) is:

Reading cts reference panel LD Score from CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/precomputation/mousebrain-test/per_annotation/mousebrain-test__ACBG.[1-22] ...
Performing regression #2/#2. CTS name is mousebrain-test__ACBG
*CTS ERROR* Caught exception during regression #2/#2. CTS name is mousebrain-test__ACBG. Exception:
Singular matrix
Results printed to CELLECT-LDSC-EXAMPLE/CELLECT-LDSC/out/prioritization/mousebrain-test__yengo.cell_type_results.txt


Because of this singular matrix error, the file with results ends up empty. I also checked the precomputation files (sending some attached) and their scores are always 0.0. Have you seen this before, or do you know why this could be happening?

[log.prioritize_annotations.mousebrain-test.yengo.txt](https://github.com/perslab/CELLECT/files/5403277/log.prioritize_annotations.mousebrain-test.yengo.txt)
[mousebrain-test__ACBG.22.annot.gz](https://github.com/perslab/CELLECT/files/5403278/mousebrain-test__ACBG.22.annot.gz)
[mousebrain-test__ACBG.22.l2.ldscore.gz](https://github.com/perslab/CELLECT/files/5403279/mousebrain-test__ACBG.22.l2.ldscore.gz)
[mousebrain-test__ACBG.22.l2.M_5_50.txt](https://github.com/perslab/CELLECT/files/5403285/mousebrain-test__ACBG.22.l2.M_5_50.txt)
[mousebrain-test__ACBG.22.l2.M.txt](https://github.com/perslab/CELLECT/files/5403286/mousebrain-test__ACBG.22.l2.M.txt)
[mousebrain-test.COMBINED_ANNOT.22.log.txt](https://github.com/perslab/CELLECT/files/5403287/mousebrain-test.COMBINED_ANNOT.22.log.txt)

**Comment by Tobi1kenobi** [comment]
Hi Daiane,

Yes, your `.annot.gz` file contains only 0.0 and whilst it should have many 0.0 values, the annot file I have previously produced from the example looks like this:
[mousebrain-test__ACBG.22.annot.gz](https://github.com/perslab/CELLECT/files/5411648/mousebrain-test__ACBG.22.annot.gz)

I really don't know what could be causing this - the code is unchanged and it is definitely working for others. I will try running the example again myself now to absolutely certain.

Tobi

**Comment by DaianeH** [comment]
Thanks, Tobi!
I noticed the error is described as CTS error, which probably come from these scripts:
https://github.com/pascaltimshel/ldsc

I wonder if the
git clone --recurse-submodules https://github.com/perslab/CELLECT.git
command worked and these are the right modified ldsc scripts I'm running.

**Comment by Tobi1kenobi** [comment]
Hey Daiane,

Yeah I'm really not sure, my fresh install worked perfectly on my system and other recent users haven't been having your issues either. I can't imagine why the LDSC scripts wouldn't install properly. Maybe git lfs isn't working correctly also on your system, that's something worth checking as the the data files wouldn't be installed. You can check this by running `git lfs env`. 

It also may be helpful to check the log for the `make_annot` rule: `CELLECT-example/logs/log.make_annot_snake.{run_prefix}.{chromosome}.txt as your annotation file seems to be the issue - that further downstream results in a singular matrix error.

Best,
Tobi

**Comment by Tobi1kenobi** [comment]
Did you have any luck fixing this @DaianeH?

**Comment by DaianeH** [comment]
Not yet, Tobi. Still working on it with the HPC team. I'm off next week, but will let you know when this is solved!
Thanks.

**Comment by DaianeH** [comment]
Hi Tobi,

I'm still working with the HPC team to solve the git lfs issue, but in the meantime another one came up.
I installed everything from scratch doing:
conda create -c conda-forge -c bioconda -n cellect3 snakemake=5.4.5
and by the time of running it, got the message:

WorkflowError in line 11 of /daiane/software/CELLECT_new3/CELLECT/rules/common_func1.smk:
Expecting Snakemake version 5.27 or higher.
  File "/daiane/software/CELLECT_new3/CELLECT/cellect-ldsc.snakefile", line 3, in <module>
  File "/daiane/software/CELLECT_new3/CELLECT/rules/common_func1.smk", line 11, in <module>

which is funny because by the time of creating the environment, the following appeared on the screen:

  added / updated specs:
    - snakemake=5.4.5
The following NEW packages will be INSTALLED:
snakemake          bioconda/noarch::snakemake-5.4.5-0
snakemake-minimal  bioconda/noarch::snakemake-minimal-5.4.5-py_0

So the version of snakemake is apparently 5.4.5, not something lower than 5.27, as the error suggests. Then I tried to run CELLECT by loading other environments that I had installed in previous months when trying to solve the CELLECT issue, in which this error did not occur, but today, this error came up by running CELLECT in all conda environments I have.

Have you seen this before?

Thank you,
Daiane.

**Comment by Tobi1kenobi** [comment]
Hey Daiane,

We've updating our suggested conda env creation command to be:
`conda install -c bioconda -c conda-forge snakemake">=5.27.4"`

5.4.5 is an earlier version of snakemake than 5.27, as the versioning does not rollover at 10 (e.g. it goes ..., 5.8, 5.9, 5.10, 5.11, ...) So please install 5.27.4 or greater and this error should be resolved.

Tobi

**Comment by DaianeH** [comment]
Oh I see now! Thanks Tobi. That worked. Only thing is that the same error as before happened: by the time of parsing the results file CELLECT-EXAMPLE/CELLECT-LDSC/out/prioritization/tabula_muris-test__BMI_Yengo2018.cell_type_results.txt , it's empty (it has only columns Name	Coefficient	Coefficient_std_error	Coefficient_P_value, so it throws an error).
I'll work more on debugging this and keep you updated. Thanks!

**Comment by DaianeH** [comment]
Hi Tobi, this seems to be solved.
The issue with git lfs is that the command git lfs install was missing. Now all files download correctly and CELLECT runs smoothly. Thanks for your help!
