### ISSUE TITLE
[BUG]: MissingOutputException in line 200 of /home/wbone/CELLECT/cellect-ldsc.snakefile: CELLECT-LDSC/precomputation/bed/genes_plus_100kb.1.bed not generated

### ISSUE THREAD

**Issue by wpbone06** [perslab/CELLECT#66]
**Describe the issue**
When I try to run CELLECT-LDSC it does not generate the  precomputation/bed/genes_plus_100kb.XX.bed files. I get the following error:
```
MissingOutputException in line 200 of /home/wbone/CELLECT/cellect-ldsc.snakefile:
Job Missing files after 5 seconds:
CELLECT-EXAMPLE/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.1.bed
CELLECT-EXAMPLE/CELLECT-LDSC/precomputation/bed/genes_plus_100kb.2.bed
...
```
When I check the CELLECT-EXAMPLE/CELLECT-LDSC/precomputation/bed/ directory after getting this error there are only these 3 files:genes_plus_100kb.oid.bed , genes_plus_100kb.size.bed , and genes_plus_100kb.version.bed.

**To Reproduce**
1. I followed the installation directions from https://github.com/perslab/CELLECT
2. I edited the example confing.yml to point to two munged summary stat files I already available.
3. I ran the following command:
`snakemake --use-conda -j -s cellect-ldsc.snakefile --configfile config_PAD_CAD_test.yml`

**Expected behavior**
I expected the CELLECT-LDSC command to run to completion using the provided example mouse brain data.

**Screenshots**

**Environment**
 - Hardware: cluster
 - OS: CentOS7 
 - CELLEX version v1.2.1
 - Environment packages and versions :
 aioeasywebdav==2.4.0
aiohttp @ file:///home/conda/feedstock_root/build_artifacts/aiohttp_1605734413565/work
amply @ file:///home/conda/feedstock_root/build_artifacts/amply_1601814141062/work
appdirs @ file:///home/conda/feedstock_root/build_artifacts/appdirs_1603108395799/work
async-timeout==3.0.1
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1605083924122/work
backports.functools-lru-cache==1.6.1
bcrypt @ file:///home/conda/feedstock_root/build_artifacts/bcrypt_1602546548323/work
biofilter==2.4.2
boto3 @ file:///home/conda/feedstock_root/build_artifacts/boto3_1609978654139/work
botocore @ file:///home/conda/feedstock_root/build_artifacts/botocore_1609974738230/work
brotlipy==0.7.0
cachetools @ file:///tmp/build/80754af9/cachetools_1607706694405/work
certifi==2020.12.5
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1606601120025/work
chardet @ file:///home/conda/feedstock_root/build_artifacts/chardet_1602255302154/work
ConfigArgParse==1.2.3
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1607606134922/work
datrie @ file:///home/conda/feedstock_root/build_artifacts/datrie_1602583309442/work
decorator==4.4.2
docutils @ file:///home/conda/feedstock_root/build_artifacts/docutils_1608036223355/work
dropbox @ file:///tmp/build/80754af9/dropbox_1606082661024/work
filechunkio==1.8
ftputil @ file:///home/conda/feedstock_root/build_artifacts/ftputil_1592165701929/work
gitdb @ file:///home/conda/feedstock_root/build_artifacts/gitdb_1588651542737/work
GitPython @ file:///home/conda/feedstock_root/build_artifacts/gitpython_1609919651081/work
google-api-core @ file:///Users/runner/miniforge3/conda-bld/google-api-core-split_1601998551628/work
google-api-python-client @ file:///home/conda/feedstock_root/build_artifacts/google-api-python-client_1605727368232/work
google-auth @ file:///home/conda/feedstock_root/build_artifacts/google-auth_1608136875028/work
google-auth-httplib2 @ file:///home/conda/feedstock_root/build_artifacts/google-auth-httplib2_1601483325475/work
google-cloud-core @ file:///home/conda/feedstock_root/build_artifacts/google-cloud-core_1608136972897/work
google-cloud-storage @ file:///home/conda/feedstock_root/build_artifacts/google-cloud-storage_1601484581504/work
google-crc32c @ file:///home/conda/feedstock_root/build_artifacts/google-crc32c_1608138311615/work
google-resumable-media @ file:///home/conda/feedstock_root/build_artifacts/google-resumable-media_1608141079349/work
googleapis-common-protos @ file:///home/conda/feedstock_root/build_artifacts/googleapis-common-protos-feedstock_1604414777091/work
grpcio @ file:///home/conda/feedstock_root/build_artifacts/grpcio_1607005041758/work
httplib2 @ file:///home/conda/feedstock_root/build_artifacts/httplib2_1590007784658/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1607975944098/work
ipython-genutils==0.2.0
Jinja2==2.11.2
jmespath @ file:///home/conda/feedstock_root/build_artifacts/jmespath_1589369830981/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1602551949684/work
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1605735002943/work
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1602267314832/work
multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1607973096815/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1602732862338/work
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1598210780226/work
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1609880972775/work
oauth2client==4.1.3
pandas==1.2.0
paramiko @ file:///home/conda/feedstock_root/build_artifacts/paramiko_1598988093657/work
prettytable @ file:///home/conda/feedstock_root/build_artifacts/prettytable_1605348622459/work
protobuf==3.14.0
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1608348952458/work
PuLP @ file:///home/conda/feedstock_root/build_artifacts/pulp_1603370434219/work
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1607352093725/work
pygraphviz @ file:///home/conda/feedstock_root/build_artifacts/pygraphviz_1602654511066/work
PyNaCl @ file:///home/conda/feedstock_root/build_artifacts/pynacl_1602614127414/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1608055815057/work
pyparsing==2.4.7
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1605115581794/work
pysftp==0.2.9
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1602326936081/work
python-dateutil==2.8.1
python-irodsclient==0.8.2
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1608904108784/work
PyYAML==5.3.1
ratelimiter @ file:///home/conda/feedstock_root/build_artifacts/ratelimiter_1602593436172/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1608156231189/work
rsa @ file:///home/conda/feedstock_root/build_artifacts/rsa_1591996208734/work
s3transfer @ file:///home/conda/feedstock_root/build_artifacts/s3transfer_1602631013510/work
simplejson @ file:///home/conda/feedstock_root/build_artifacts/simplejson_1607639730461/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
slacker==0.14.0
smmap @ file:///home/conda/feedstock_root/build_artifacts/smmap_1588651577140/work
snakemake @ file:///opt/conda/conda-bld/snakemake_1608588801954/work
toposort @ file:///home/conda/feedstock_root/build_artifacts/toposort_1608294411535/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1602771532708/work
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1602702424206/work
uritemplate==3.0.1
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1605225765842/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
wrapt @ file:///home/conda/feedstock_root/build_artifacts/wrapt_1606141220149/work
xmlrunner==1.7.7
yarl @ file:///home/conda/feedstock_root/build_artifacts/yarl_1605429469302/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1603668650351/work

**Additional context**
Add any other context about the problem here, e.g. sample data.

**Comment by Tobi1kenobi** [comment]
Hi there,

I suspect you've installed CELLECT incorrectly. This looks like a git lfs issue as the file that should be iterated over is stored in this repo with git lfs and instead of iterating over chromosomes it is iterating over "version", "oid", and "size" which are the first columns if the file isn't unpacked properly upon installation.

I recommend [reinstalling](https://github.com/perslab/CELLECT/#installation) and paying close attention to the git lfs steps. You can check the data files have been properly unpacked after installing with 'less data/ldsc/GRCh37-chr-sizes.txt' from within the CELLECT directory.

Hope that helps,
Tobi

**Comment by wpbone06** [comment]
Thanks Tobi!

I will try reinstalling git lsf and let you know if I continue to have
issues.

Best,
Will

**Comment by wpbone06** [comment]
Hi Tobi,

I have been working with the cluster support team, and we are still having
issues getting the data/ldsc/GRCh37-chr-sizes.txt, w_hm3.snplist, and
data/ldsc/print_snps.txt files to unpack correctly. Could you send me an
example output of the "git lfs env" command that has worked for installing
CELLECT?

Also, here is the current result of git lfs env I am getting:

git lfs env
git-lfs/2.2.1 (GitHub; linux amd64; go 1.8.3; git 621d1f82)
git version 2.17.0

LocalWorkingDir=/home/wbone/CELLECT_test
LocalGitDir=/home/wbone/CELLECT_test/.git
LocalGitStorageDir=/home/wbone/CELLECT_test/.git
LocalMediaDir=/home/wbone/CELLECT_test/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/wbone/CELLECT_test/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge"
git config filter.lfs.clean = "git-lfs clean"

Please let me know if you see anything that looks odd to you!

Thank you,
Will

**Comment by Tobi1kenobi** [comment]
Hi Will,

No, unfortunately strangely that all looks fine to me - I can't say I know enough about git lfs to debug it further than this as it has worked on all the systems I have installed CELLECT on (three local systems and two clusters). One simple solution might be installing git lfs and CELLECT locally (if the cluster is the issue) then scp'ing the data folder over to your cluster. 

If this still doesn't work, let me know and I can see about temporarily putting the data files in a GDrive folder for you.

Best,
Tobi
