### ISSUE TITLE
Offline-mode available?

### ISSUE THREAD

**Issue by demodw** [perslab/CELLECT#74]
Hi,

I'm trying to run CELLECT, but since I am working on a server with no internet connection, it's not possible to add the -use-conda flag (packages simply cannot be downloaded). This complicates the pipeline because it is not able to run ldsc with the python2 interpreter. Is there any workaround for this?

Furthermore, it seems like bedtools is a requirement but I don't see this listed anywhere. I had to randomly load some modules until I no longer got errors.

**Comment by Tobi1kenobi** [comment]
Hi David,

As of this moment there is no offline mode available as CELLECT is maintained on this GitHub and cannot be installed without an active internet connection. Presumably you installed it locally then copied it over to the server, what you could try is this command locally:
```
snakemake --use-conda -j -s cellect-ldsc.snakefile --configfile config.yml **--conda-create-envs-only**
```
Then once the envs are created, copy CELLECT over to your server with no internet. This is the recommended by the [snakemake documentation](https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html?highlight=conda#integrated-package-management) for situations such as yours.

Bedtools is a requirement for pybedtools which we use in [scripts/make_annot_from_geneset_all_chr_snake.py](https://github.com/perslab/CELLECT/blob/master/scripts/make_annot_from_geneset_all_chr_snake.py#L83). It is installed as a dependency by conda despite not being explicitly specified in the env yamls.

Hope this helps,
Tobi
