### ISSUE TITLE
Issue with dependencies?

### ISSUE THREAD

**Issue by Hannahglover** [perslab/CELLECT#78]
Hello

I am having trying to run the CELLECT examples prior to subbing in my own data. I have reviewed the documentation, and have successfully munged the summary statistics, downloaded. I am having issues running the last step of CELLECT-lcsd and CELLECT-magma, and I _think_ its an issue with dependencies on my end. I have attached the errors from both options: [CELLECT_LDSCError_25FEB22.txt](https://github.com/perslab/CELLECT/files/8143738/CELLECT_LDSCError_25FEB22.txt) and [CELLECT_MagmaError_25FEB22.txt](https://github.com/perslab/CELLECT/files/8143739/CELLECT_MagmaError_25FEB22.txt). I think they are converging on an issue with importing numpy.

Tried troubleshooting as much as my R-centric mind can handle, but I am hoping this is a straightforward error.

I am running the following:
anaconda                  2021.11                  py39_0  
anaconda-client           1.9.0            py39hecd8cb5_0  
anaconda-navigator        2.1.1                    py39_0  
anaconda-project          0.10.1             pyhd3eb1b0_0  
conda                     4.11.0           py39h6e9494a_0    conda-forge
pandas                    1.3.4            py39h743cdd8_0  
numpy                     1.20.3           py39h4b4dc7a_0  
python                    3.9.7                h88f2d9e_1  
snakemake                 6.15.5               hdfd78af_0    bioconda

Please let me know if I am missing something, or if you need additional info. Thanks very much!

**Comment by Hannahglover** [comment]
Hi Tobi,

Thanks for getting back to me. I tried deleting .snakemake and reinstalling but I am having the same issue. I have played around with making the CELLECT folder a conda environment but haven't had any success. 

Here is the results of the commands you asked for:
[Conda List - 28FEB22.txt](https://github.com/perslab/CELLECT/files/8154833/Conda.List.-.28FEB22.txt)

Let me know if you have any other ideas.
Hannah

**Comment by Tobi1kenobi** [comment]
The error was that somehow one of the conda environments installed automatically behind the scenes (https://github.com/perslab/CELLECT/blob/master/envs/cellectpy3.yml) as part of CELLECT had installed a broken version of numpy v1.16.3.

I resolved this with @Hannahglover by:
```
conda activate /Users/claudiadoege/CELLECT/.snakemake/conda/97c761b82a988c41e9bcad44011fa9b4
conda install -c conda-forge numpy=1.16.4
```

I might update the `cellectpy3.yml` to numpy=1.16.4 or greater if I have time to test that:
a) It is the root of the problem and I can reproduce it
b) Changing the yaml fixes the problem

Closing this issue for now as it is resolved for Hannah.
