### ISSUE TITLE
Error in git clone

### ISSUE THREAD

**Issue by grimwoo** [perslab/CELLECT#80]
Thanks for the decelopment of such a nice program.

I encountered the error when `sudo git clone --recurse-submodules https://github.com/perslab/CELLECT.git`. Could anyone please help me?

Error information:
`
Cloning into 'CELLECT'...
remote: Enumerating objects: 1333, done.
remote: Counting objects: 100% (213/213), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 1333 (delta 128), reused 211 (delta 128), pack-reused 1120
Receiving objects: 100% (1333/1333), 8.52 MiB | 2.29 MiB/s, done.
Resolving deltas: 100% (642/642), done.
Updating files: 100% (273/273), done.
Downloading data/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.bed (96 MB)
Error downloading object: data/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.bed (13daae3): Smudge error: Error downloading data/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.bed (13daae3e06a3e6fd77cc9f5792fc53c8f2ab9ba0c95fef818f78d4d2b7c94287): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /mnt/c/Users/grimw/CELLECT/.git/lfs/logs/20220609T155333.5466763.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: data/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.bed: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
`

**Comment by pascaltimshel** [comment]
Thanks for letting us know. The problem with `This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.` has now been fixed.
